---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-mysql
  namespace: default
  labels:
    app: RELEASE-NAME-mysql
    chart: "mysql-1.6.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
type: Opaque
data:
  
  
  mysql-root-password: "UWFPamN4NmVKcA=="
  
  
  
  
  mysql-password: "V0wyT3J5Q3lGbA=="
